"""empty message

Revision ID: c7cc84d44c9a
Revises: d33ebb625f57
Create Date: 2024-12-18 10:21:26.482177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cc84d44c9a'
down_revision = 'd33ebb625f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['to_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['from_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('to_account_id')
        batch_op.drop_column('from_account_id')

    # ### end Alembic commands ###
