"""empty message

Revision ID: d9145ded1947
Revises: 703fc3991e1d
Create Date: 2024-12-18 11:08:43.649873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9145ded1947'
down_revision = '703fc3991e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=55),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=55),
               nullable=False)

    # ### end Alembic commands ###
